#!/bin/sh
# makeconf $Id: makeconf 3314 2008-03-05 04:12:56Z Fish $

if [ "$1" ] ; then
	NEOSTATSCONF=$1
else
	NEOSTATSCONF="neostats.conf"
fi

TIME=`date +"%H:%M:%S %Z"`
DATE=`date +"%a, %b %e %Y"`
SERVNAME="Neo.SomeIRC.net"
ROOTNICK="NeoStats"
SERVICEHOST="neostats.net"
SERVNUMERIC="1"
INFOLINE="NeoStats 3.0 IRC Services"
LINKPORT="6667"
LINKSERVER="127.0.0.1"
LINKPASS="linkpassword"
NEOCHAN="#services"
NEOCONN="10"
BINDIP="127.0.0.1 <- CHANGETHIS!!"
LOGFNAMEFORMAT="-%m-%d"
SETSERVERTIMES="24"
DATABASE="gdbm"

# these are so I can use stuff like $1 without it replacing it...like by
# using $dlrsgn$uno for $1
dlrsgn="$"
uno="1"
dos="2"

# remove the temp file if it exists
rm -f mkconf.tmp

# make a quick script for replacing one line with another

cat > repl_str << __EOF__
sed -e "s@^$dlrsgn$uno\(.*\)@$dlrsgn$dos" $NEOSTATSCONF > mkconf.tmp
cp mkconf.tmp $NEOSTATSCONF
rm mkconf.tmp
__EOF__

# mark repl_str as an executable
chmod +x repl_str
rm -f repl_str
# Checking out how to specify not to make a new line with the current OS
c=''
n=''
2>/dev/null
if [ "`eval echo -n 'a'`" = "-n a" ]; then
	c='\c'
else
	n='-n'
fi

# If Settings exist, load the info, otherwise tell them to run configure.

if [ -r config.h ]; then
	echo "Starting configuration.. "
else if [ -r include/config.h ]; then
	echo "Starting configuration.. "
else
	echo "Configuration failed!"
	echo "You have not run configure yet!"
	echo "You probably should read the README file too"
	echo ""
	echo "Type ./configure"
	echo "(If you need help read the README before asking us)"
	echo ""
	exit 1
fi
fi
CONF=$NEOSTATSCONF

if [ -r "$CONF" ]; then
	echo "$NEOSTATSCONF found"
	echo " "
	echo "You already have a configuration file. This script is just for"
	echo "creating the configuration file. If you continue you WILL LOSE"
	echo "all the data that is already in your configuration file!"
	echo ""
	echo "If you are sure you want to recreate your configuration file"
	echo "type 'recreate'."
	echo $n " [exit] -> $c"
	read cc

	if [ "$cc" != "recreate" ]; then
		echo " "
		echo "Do you want to edit $NEOSTATSCONF using an editor?"
		echo "If so, specify the editor you want to use. Otherwise,"
		echo "type 'exit'."
		EDITFND="not found"

                if [ -r /usr/bin/pico ]; then
                        EDITFND="pico"
                fi

                if [ -r /usr/bin/joe ]; then
                        EDITFND="joe"
                fi

		if [ -r /usr/bin/nano ]; then
			EDITFND="nano"
		fi

		if [ -r /usr/bin/vim ]; then
			EDITFND="vim"
		fi

		while [ "c" = "c" ]; do
			echo $n " [$EDITFND] -> $c"
			read EDITOR

			if [ -z "$EDITOR" ]; then
				EDITOR="$EDITFND"
			fi

			if [ "$EDITOR" = "exit" ]; then
				echo "Done."
				exit 1
			fi

			if [ -f $EDITOR ]; then
				$EDITOR $CONF
				exit 1
			fi

			if [ -f /usr/bin/$EDITOR ]; then
				/usr/bin/$EDITOR $CONF
				exit 1
			fi

			echo "Editor not found. Specify a valid editor or"
			echo "type 'exit' to quit this script."
		done

	fi

	mv $CONF "$CONF.saved"
	rm $CONF
	echo "$NEOSTATSCONF has been renamed to $CONF.saved"
else
	echo "$NEOSTATSCONF is not found. (good)"
fi

clear
echo ""
echo "Thanks for Choosing NeoStats!"
echo ""
echo "*----------------------------------------*"
echo "| Welcome to the $NEOSTATSCONF generator. |"
echo "*----------------------------------------*"

###########################################################################
# select IRCd
validselection=0
echo "Which IRC server do you use?"
echo "     1) Unreal 3.1.x"
echo "     2) Unreal 3.2.x"
echo "     3) Ultimate 2.x.x"
echo "     4) Ultimate 3.x.x"
echo "     5) Hybrid7"
echo "     6) Bahamut 1.4"
echo "     7) Bahamut 1.8"
echo "     8) Plexus"
echo "     9) IRCu P10"
echo "     10) Asuka"
echo "     11) Nefarious"
echo "     12) Inspircd 1.1"
echo "     13) InspIRCd 2.0"
while [ $validselection -eq 0 ] ; do
	echo $n " [$IRCD_DEFAULT] -> $c"
	if read INPUT ; then : ; else echo "" ; exit 1 ; fi
	if [ ! "$INPUT" ] ; then
		INPUT=$IRCD_DEFAULT
	fi
	case $INPUT in
		no\ default)
			echo "You must specify your IRC server type in order for NeoStats to function"
			echo "correctly."
			;;
		1)
 			IRCD="unreal31"
			validselection=1
			;;
		2)
 			IRCD="unreal32"
			validselection=1
			;;
		3)
			IRCD="ultimate2"
			validselection=1
			;;
		4)
			IRCD="ultimate3"
			validselection=1
			;;
		5)
			IRCD="hybrid7"
			MEXTAUTHALLOWED=0
			validselection=1
			;;
		6)
			IRCD="bahamut14"
			validselection=1
			;;
		7)
			IRCD="bahamut18"
			validselection=1
			;;
		8)
			IRCD="plexus"
			validselection=1
			;;
		9)
			IRCD="ircup10"
			validselection=1
			;;
		10)
			IRCD="asuka"
			validselection=1
			;;
		11)
			IRCD="nefarious"
			validselection=1
			;;
		12)
			IRCD="inspircd"
			validselection=1
			;;
                13)
                        IRCD="inspircd20"
                        validselection=1
                        ;;
		*)
			echo "Please enter a valid option number."
			;;
	esac
done
IRCD_DEFAULT=$INPUT
echo ""

echo " "
echo "What will your root nickname be? (ie: $ROOTNICK)"
echo $n " [$ROOTNICK] -> $c"
read cc
if [ ! -z "$cc" ]; then
	ROOTNICK="$cc"
fi

echo " "
echo "What will your service host be? (ie: $SERVICEHOST)"
echo $n " [$SERVICEHOST] -> $c"
read cc
if [ ! -z "$cc" ]; then
	SERVICEHOST="$cc"
fi

echo " "
echo "What will your server name be? (ie: $SERVNAME)"
echo $n " [$SERVNAME] -> $c"
read cc
if [ ! -z "$cc" ]; then
	SERVNAME="$cc"
fi

echo " "
echo "What is your IRC server's IP? (ie: $LINKSERVER)"
echo $n " [$LINKSERVER] -> $c"
read cc
if [ ! -z "$cc" ]; then
        LINKSERVER="$cc"
fi

echo " "
echo "What is the IRCd's Link port? (ie: 7890)"
echo $n " [$LINKPORT] -> $c"
read cc
if [ ! -z "$cc" ]; then
        LINKPORT="$cc"
fi

echo " "
echo "What is the IRCd's Link password for stats? (ie: bleh)"
echo $n " [$LINKPASS] -> $c"
read cc
if [ ! -z "$cc" ]; then
         LINKPASS="$cc"
fi

echo " "
echo "NeoStats Server comment?"
echo $n " [$INFOLINE] -> $c"
read cc
if [ ! -z "$cc" ]; then
	INFOLINE="$cc"
fi

echo " "
echo "What channel should NeoStats join on IRC?"
echo $n " [$NEOCHAN] -> $c"
read cc
if [ ! -z "$cc" ]; then
        NEOCHAN="$cc"
fi

echo " "
echo "Time in seconds we wait before attempting to reconnect to the server on a split?"
echo $n " [$NEOCONN] -> $c"
read cc
if [ ! -z "$cc" ]; then
        NEOCONN="$cc"
fi

echo " "
echo "What IP should NeoStats Bind to? (ie: 203.208.228.144)"
echo "This is optional. See neostats.conf for more information"
echo $n " [$BINDIP] -> $c"
read cc
if [ ! -z "$cc" ]; then
        BINDIP="$cc"
fi

cat > $CONF << __EOF__
##################################################
## Configuration file for NeoStats
## Created:  $DATE - $TIME
## NeoStats Copyright (c) 2011-2030, Tom Mcloughlin, Jack Wain
## Web: http://www.NeoStats.Net
## File Revision: 3.0
##################################################

##################################################
#Each of the options has an indicator as follows:
#    [REQUIRED]    - must be set or NeoStats will not run.
#    [RECOMMENDED] - optional but may cause problems if not set.
#    [OPTIONAL]    - optional and the feature will be disabled if not set.
#    [DISCOURAGED] - may cause undesirable side effects if enabled.
##################################################

#################################
# NeoStats Server Configuration #
#################################

ServerConfig {
# NAME = "<hostname>" [REQUIRED]
#    Specifies the name of the NeoStats Server as it will appear on 
#    the network. e.g. 
#      
#          SERVER_NAME = "stats.neostats.net"
#      
#    When NeoStats links, it will appear as stats.neostats.net.
  Name = "$SERVNAME"

# INFO = "<info line>" [REQUIRED]
#    Specify the description of the server that
#    appears when you do /links e.g.
#    
#        INFO "Network Auxiliary Services"
  Info = "$INFOLINE"

# SERVICECHANNEL="#<channel name>" [REQUIRED]
#    Specify the channel that all bots on NeoStats
#    will automatically join, and echo out any
#    important information e.g.
#    
#        SERVICECHANNEL="#services"
#        
#    Makes NeoStats, and all the other bots join #services channel on 
#    start-up/load.
  ServiceChannel = "$NEOCHAN"

# SERVER_NUMERIC = <numeric> [RECOMMENDED]
#    Specify the numeric of the server to send on connect.
#    This must be a value between 1 and 254, and must not be in use by
#    any other IRC server on the network.  
#    
#        SERVER_NUMERIC = 1
  ServerNumeric = $SERVNUMERIC

# BINDTO = <ip address or hostname> [OPTIONAL]
#    Make NeoStats bind to a particular IP Address. If not
#    specified NeoStats will attempt to find this address
#    itself. e.g. 
#    
#        BINDTO 203.203.123.12
#    
#    All outgoing connections from NeoStats will originate from this 
#    IP address
#    This IP address should not be localhost (127.0.0.1)
  BindTo = "$BINDIP"

# PROTOCOL = "<protocol>" [REQUIRED]
#    Specifies the protocol module to use.
#    Valid protocol options are:
# 		unreal31 unreal32 ultimate2 ultimate3
#		hybrid7 bahamut14 bahamut18 plexus
#		ircup10 asuka nefarious
#       client
#
#          PROTOCOL = "unreal32"
#      
  Protocol = "$IRCD"
}

#################################
# NeoStats Option Configuration #
#################################


Options {
# RECONNECTTIME = <seconds> [RECOMMENDED]
#    If NeoStats server gets split from the network, how long to wait 
#    before attempting to reconnect to the network. A value of 0 will 
#    cause NeoStats to shutdown and not attempt to reconnect.
  ReconnectTime = $NEOCONN

# USEPRIVMSG = <true/false> [DISCOURAGED]
# Will Tell the Bots to Pm The User insted of 'Notice'
  UsePrivmsg = false

# OPERONLY = <true/false> [OPTIONAL]
# Restrict NeoStats and StatServ to Oper Use Only. 
  OperOnly = false

# SERVERSETTIME=<INTERVAL> [OPTIONAL]
# Sync's the clocks every 24 hours
  ServerSettime = 24

# DatabaseType = "<dbm>" [OPTIONAL]
#    Specifies the database manager module to use.
#    NeoStats will default to GDBM if this is not provided.
#    Valid options are:
#          gdbm
#          bdb (if found during configure)
#
#          DatabaseType = "gdbm"
#      
#
  DatabaseType = "$DATABASE"

# LOGFILENAMEFORMAT = "<format>" [OPTIONAL]
#    Defines the format for dated log files. This allows you to choose 
#    what date format is used for log file names when they are rotated at 
#    midnight. The option uses the parameters passed to strftime so you 
#    can use any options valid for that function. Common ones are:
#        %a  Abbreviated weekday name 
#        %A  Full weekday name 
#        %b  Abbreviated month name 
#        %B  Full month name 
#        %d  Day of month as decimal number (01 – 31) 
#        %m  Month as decimal number (01 – 12) 
#        %y  Year without century, as decimal number (00 – 99) 
#        %Y  Year with century, as decimal number 
#
#    Examples using 30 September 2003 as the date:
#    For NeoStats0930.log:
#        
#        LOGFILENAMEFORMAT="%m%d"
#    
#    For NeoStats20030930.log:
#    
#        LOGFILENAMEFORMAT="%Y%m%d"
#    
#    If not defined, the default is the original NeoStats log format of
#    "-%m-%d" i.e. NeoStats-09-30.log
  #LogFileNameFormat = "$LOGFNAMEFORMAT"

# ROOTNICK = "<nick>" [REQUIRED]
#    Specifies the nick of the NeoStats root bot
#    e.g. 
#      
#          ROOTNICK="NeoStats"
#      
#    When NeoStats links, it create a root bot with nick NeoStats
  RootNick = "$ROOTNICK"

# SERVICESHOST = "<hostname>" [REQUIRED]
#    Specifies the default host of NeoStats service bots
#    e.g. 
#      
#          SERVICEHOST="stats.net"
#      
#    Service bots will now we user@stats.net
#    If not specified NeoStats will default to the server name
  ServicesHost = "$SERVICEHOST"

# NOLOAD = true [YOU MUST REMOVE THIS]
# You must change this to false this is only here to make sure you have read the config file
  NOLOAD = false
}

##################################
# NeoStats Linking Configuration #
##################################

# This section defines the Server that NeoStats will
# attempt to link to. You must configure this server
# with the correct C/N and U lines for Neostats

Servers {

# IPADDRESS ="<ip address or hostname>" [REQUIRED]
  IpAddress = "$LINKSERVER"

# PORT = <port number> [REQUIRED]
#    Specifies the port to connect to on the IRC Server e.g.
#    
#        PORT=6667        
#    
#    When connecting, NeoStats will connect to port 6667
  Port = $LINKPORT

# PASSWORD="<link password>" [REQUIRED]
#    Specifies the password used to connect. This must match your C/N 
#    lines in your IRCD configuration e.g.
#  
#      PASSWORD="linkpass"
#      
#    Send "linkpass" as the password to connect
  Password = "$LINKPASS"
}


########################################
# NeoStats Administrator Configuration #
########################################


ServiceRoot {
#MASK="<nick!ident@host>" [REQUIRED]
#    Who should get master access to manage NeoStats regardless of 
#    authentication systems. Only one entry allowed. e.g.
#    
#        MASK="fish!?Fish@*.neostats.net"
#        
#    Will give "fish" complete access to NeoStats if fish has 
#    umode +r and comes from the specified hostname and ident. 
  #Mask = "ircop!*@*"
}


#################################
# NeoStats Module Configuration #
#################################

Modules {
#####################################
# Module Configurations and Loading #
#####################################

# MODULENAME = {"<module name>", "<module name>", "<module_name>"} [OPTIONAL]
#    What modules to load at start-up. e.g. 
#        
#        MODULENAME = { "statserv" }
#    
#    Will load up StatServ only at boot
#    
#    To specify NeoStats to load multiple modules, place a comma after
#    each module and specify the next one e.g.
#
#        MODULENAME = { "statserv", "extauth" }
#
#    will load up both statserv and extauth modules
#    
#    We have provided example lines for convenience for 
#    official modules but you must download and install
#    external modules before trying to load them.

MODULENAME = {
# Update notification module, loaded by default
        "update",
        
# StatServ, maintain and report various networks statistics
	"statserv",

# HostServ, vhost services for users
	"hostserv",

# TextServ, text messaging service
	"textserv",

# ConnectServ, monitor connections to the network
# This is disabled by Default as it causes NeoStats to Crash *Durin a Botnet* 
# and is not recommended if you want this module please uncomment it (#)
#	"connectserv",

# Operlog, operator command logging service
	"operlog",

# IRCdauth, authenticate users based on their user modes.
	"ircdauth",

# Extauth, authenticate users based on nick!user@host access lists
	"extauth",

# QuoteServ, Quote Message Service
#	"quoteserv",

# LimitServ, Channel Limit Setting Service
#	"limitserv",

# SecureServ. You must download and install SecureServ first.
#	"secureserv",

# BLSB. You must download and install BLSB first.
#	"blsb",

# OPSB. You must download and install OPSB first.
#	"opsb",

# LogServ. You must download and install LogServ first.
#	"logserv",

# TriviaServ. You must download and install TriviaServ first.
#	"triviaserv",

# WarServ. You must download and install WarServ first.
#	"warserv",

# GamesServ. You must download and install GameServ first.
#	"gamesserv",

# YahzteeServ. You must download and install YahzteeServ first.
#	"yahtzeeserv",

# FloodServ. You must download and install FloodServ first.
	"floodserv",

# SeenServ. You must download and install SeenServ first.
#	"seenserv",

# ProfileServ. You must download and install ProfileServ first.
#	"profileserv",

}
}

#####################################
# NeoNetConfigurations and Loading  #
#####################################

# NeoNet is a protocol that links all NeoStats installations back to the main
# NeoStats sites, such as http://secure.irc-chat.net etc.
# This allows you to take advantage of some of the aditional features or modules
# that we support, such as updated definitions for SecureServ accounts, or 
# reporting options for OPSB.

# You must visit http://accounts.neostats.net/ to create your NeoNet account
# and select what aditional options you would like. (some might require 3rd
# party modules, such as SecureServ or OPSB). 

# If you have been using SecureServ on the 2.5 series, please visit
# http://accounts.neostats.net/migrate/ for information on how to 
# use your existing Secure.irc-chat.net account with NeoNet.
NeoNet {

# This is the username, as supplied on the NeoNet pages.
# It should be your IRC Network user account and not your 
# personal accounts. 
#        UserName = "somenet"

# This is your IRC Network User account password.
#        PassWord = "password"

# Leave the port at 2960 unless otherwise instructed.
#        Port = 2960

# This option handles how NeoNet connections are established. The available
# options are:
#	yes 	- Connect to NeoNet during startup
#	no 	- Never connect to NeoNet (Note, some features might not work if Connect
#	     	is set to No
#	demand 	- Only connect to NeoNet when there is a pending NeoNet Message
#	     	to be sent. 
	Connect = "yes"
}                                

###############################################################################
## End of Configuration                                                      ##
###############################################################################


__EOF__


# Make it so ONLY the one who created the conf can read or write.
chmod 700 $NEOSTATSCONF

echo ""
echo "`------------------------------------------------`"
echo "| Thank you for choosing NeoStats.               |"
echo "| You must now edit neostats.conf and check all  |"
echo "| settings are correct then just type ./neostats |"
echo "| to run NeoStats. NeoStats will not run until   |"
echo "| you do not edit this file.                     |"
echo "`------------------------------------------------`"
echo 
exit 1
